NUMPY 

NumPy is python Library used for working with arrays. 
An arrays is a collection of data with same datatype  stored in contiguous memory. Array is somewhat similar to list and has function for working in domain like Mathematicians, Linear Algebra etc.
NumPy was created in year 2005 by Travis Oliphant, it is open source library can be used freely.
NumPy stands for Numerical Python.

Why we use NumPy?
In Python we already have list that do the same purpose as array. But it is slower is process.
NumPy aims to provide an array object that is 50X faster than list. The array object in NumPy is ndarray
which means numpy dimensional array-----Nd stands for numpy dimensional arrays are frequently used in DS where speed is very important in performing certain task. Data should bbe of same datatype in Numpy.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: C:\Users\Admin\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np 

In [3]:
array1=np.array([2,4,6,7,8,9,10]) #1D array =====Series
#print(array1)
array1

array([ 2,  4,  6,  7,  8,  9, 10])

In [4]:
a2=np.array([[100,200,300],[101,102,103],[5,6,7]])  # 2D array ====Data ====LIST UNDER LIST
a2 
#All arrays should be equal or else it will throw error inhomogenuous shape or
#if we old jupyter version then it declare that array as list

array([[100, 200, 300],
       [101, 102, 103],
       [  5,   6,   7]])

In [5]:
a3=np.array([[[10,20,30],[1,3,4],[4,5,6],[80,70,90]]]) # 3D array 
print(a3)

[[[10 20 30]
  [ 1  3  4]
  [ 4  5  6]
  [80 70 90]]]


In [6]:
#To check the dimension of array

print(array1.ndim) #ndim is function to check dimension of an array
print(a2.ndim)
print(a3.ndim)

1
2
3


In [7]:
# To check the shape of array

array1.shape

(7,)

In [8]:
a2.shape

(3, 3)

In [9]:
a3.shape

(1, 4, 3)

In [10]:
a4=np.array([[[1,2,3],["Satvika","Umesh","Harry"]],[["Mumbai","Thane","Palghar"],
                                                    [20,25,26]]])

In [11]:
print(a4)

[[['1' '2' '3']
  ['Satvika' 'Umesh' 'Harry']]

 [['Mumbai' 'Thane' 'Palghar']
  ['20' '25' '26']]]


In [12]:
a4.shape

(2, 2, 3)

In [13]:
a5=np.array([[[2,4],[5,6]],[[10,12],[14,15]],[[11,15],[74,75]],
             [[100,101],[102,103]]])

In [14]:
print(a5)

[[[  2   4]
  [  5   6]]

 [[ 10  12]
  [ 14  15]]

 [[ 11  15]
  [ 74  75]]

 [[100 101]
  [102 103]]]


In [15]:
a5.shape

(4, 2, 2)

In [16]:
#To check size of array ==== to count no of element in the array

print(array1.size)
print(a2.size)
print(a3.size)
print(a4.size)
print(a5.size)

7
9
12
12
16


In [17]:
data=np.array([[20,25,26,27,28,29],
               ["Satvika","Harry","Manish","Isha","Pratik","Mohan"]])

In [18]:
print(data)

[['20' '25' '26' '27' '28' '29']
 ['Satvika' 'Harry' 'Manish' 'Isha' 'Pratik' 'Mohan']]


In [19]:
#TRANSPOSE the array means rows into column or columns into row

data.T   #T stands for Transpose

array([['20', 'Satvika'],
       ['25', 'Harry'],
       ['26', 'Manish'],
       ['27', 'Isha'],
       ['28', 'Pratik'],
       ['29', 'Mohan']], dtype='<U11')

In [20]:
data.shape

(2, 6)

In [21]:
#Reshape is used for moulding matrix as per your needs

data.reshape(4,3) 

array([['20', '25', '26'],
       ['27', '28', '29'],
       ['Satvika', 'Harry', 'Manish'],
       ['Isha', 'Pratik', 'Mohan']], dtype='<U11')

In [22]:
data.reshape(3,4)

array([['20', '25', '26', '27'],
       ['28', '29', 'Satvika', 'Harry'],
       ['Manish', 'Isha', 'Pratik', 'Mohan']], dtype='<U11')

In [23]:
data

array([['20', '25', '26', '27', '28', '29'],
       ['Satvika', 'Harry', 'Manish', 'Isha', 'Pratik', 'Mohan']],
      dtype='<U11')

In [24]:
data.reshape(1,4,3)

array([[['20', '25', '26'],
        ['27', '28', '29'],
        ['Satvika', 'Harry', 'Manish'],
        ['Isha', 'Pratik', 'Mohan']]], dtype='<U11')

In [25]:
data.reshape(2,2,3)

array([[['20', '25', '26'],
        ['27', '28', '29']],

       [['Satvika', 'Harry', 'Manish'],
        ['Isha', 'Pratik', 'Mohan']]], dtype='<U11')

In [26]:
data.reshape(4,3,1)

array([[['20'],
        ['25'],
        ['26']],

       [['27'],
        ['28'],
        ['29']],

       [['Satvika'],
        ['Harry'],
        ['Manish']],

       [['Isha'],
        ['Pratik'],
        ['Mohan']]], dtype='<U11')

In [27]:
a5


array([[[  2,   4],
        [  5,   6]],

       [[ 10,  12],
        [ 14,  15]],

       [[ 11,  15],
        [ 74,  75]],

       [[100, 101],
        [102, 103]]])

In [28]:
a5.reshape(2,2,4)

array([[[  2,   4,   5,   6],
        [ 10,  12,  14,  15]],

       [[ 11,  15,  74,  75],
        [100, 101, 102, 103]]])

In [29]:
a5.reshape(1,8,2)

array([[[  2,   4],
        [  5,   6],
        [ 10,  12],
        [ 14,  15],
        [ 11,  15],
        [ 74,  75],
        [100, 101],
        [102, 103]]])

In [30]:
a5.reshape(8,2)

array([[  2,   4],
       [  5,   6],
       [ 10,  12],
       [ 14,  15],
       [ 11,  15],
       [ 74,  75],
       [100, 101],
       [102, 103]])

In [31]:
A=np.array([1,2,200,40,50,48,75,9,12,23,45,65,10,1,4,5,78,250]).reshape(3,3,2)

In [32]:
A.size


18

In [33]:
A

array([[[  1,   2],
        [200,  40],
        [ 50,  48]],

       [[ 75,   9],
        [ 12,  23],
        [ 45,  65]],

       [[ 10,   1],
        [  4,   5],
        [ 78, 250]]])

ZEROS ARRAY

In [34]:
azero=np.zeros(5) #1D array
print(azero) #zeros are always in float

[0. 0. 0. 0. 0.]


In [35]:
bzero=np.zeros((4,5)) #2D array
print(bzero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
czero=np.zeros((3,2,3)) #3d array
print(czero)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


ONES ARRAYS

In [37]:
A1=np.ones(6) #1d array
print(A1) #ones function also gives 1 in float value

[1. 1. 1. 1. 1. 1.]


In [38]:
A2=np.ones((3,3)) # 2Darray
print(A2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
A3=np.ones((2,3,2)) #3D array
print(A3)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


EMPTY ARRAY====RANDOM DATA

In [40]:
emp1=np.empty(5) #1D 
print(emp1)

[0. 0. 0. 0. 0.]


In [41]:
emp2=np.empty((2,4)) #2D
print(emp2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
emp3=np.empty((2,3,3)) #3D
print(emp3)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [43]:
#ARANGE 

arr1=np.arange(10) #stop 
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
arr2=np.arange(1,31) #start , stop
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [45]:
arr3=np.arange(1,51,2) #start stop step
print(arr3)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [46]:
arr3=np.arange(1,51,2).reshape(5,5)
print(arr3)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [47]:
arr4=np.arange(1,61,3).reshape(2,5,2)
#print(arr4.size)
print(arr4)


[[[ 1  4]
  [ 7 10]
  [13 16]
  [19 22]
  [25 28]]

 [[31 34]
  [37 40]
  [43 46]
  [49 52]
  [55 58]]]


In [48]:
#### LINSPACE

arr6=np.linspace(1,10,25) #start,endnum, no of elements we want
#It will give data after spliting the range on equal intervals
print(arr6)

[ 1.     1.375  1.75   2.125  2.5    2.875  3.25   3.625  4.     4.375
  4.75   5.125  5.5    5.875  6.25   6.625  7.     7.375  7.75   8.125
  8.5    8.875  9.25   9.625 10.   ]


In [49]:
arr7=np.linspace(100,200,75)
print(arr7)

[100.         101.35135135 102.7027027  104.05405405 105.40540541
 106.75675676 108.10810811 109.45945946 110.81081081 112.16216216
 113.51351351 114.86486486 116.21621622 117.56756757 118.91891892
 120.27027027 121.62162162 122.97297297 124.32432432 125.67567568
 127.02702703 128.37837838 129.72972973 131.08108108 132.43243243
 133.78378378 135.13513514 136.48648649 137.83783784 139.18918919
 140.54054054 141.89189189 143.24324324 144.59459459 145.94594595
 147.2972973  148.64864865 150.         151.35135135 152.7027027
 154.05405405 155.40540541 156.75675676 158.10810811 159.45945946
 160.81081081 162.16216216 163.51351351 164.86486486 166.21621622
 167.56756757 168.91891892 170.27027027 171.62162162 172.97297297
 174.32432432 175.67567568 177.02702703 178.37837838 179.72972973
 181.08108108 182.43243243 183.78378378 185.13513514 186.48648649
 187.83783784 189.18918919 190.54054054 191.89189189 193.24324324
 194.59459459 195.94594595 197.2972973  198.64864865 200.        ]


In [50]:
arr8=np.linspace(100,150,25,endpoint=False)
#endpoint=False means in no of elements end num will not be included
print(arr8)


[100. 102. 104. 106. 108. 110. 112. 114. 116. 118. 120. 122. 124. 126.
 128. 130. 132. 134. 136. 138. 140. 142. 144. 146. 148.]


In [51]:
#EYE MATRIX DIAGONAL=====0 1 Matrix ===Itdentity Matrix

eye1=np.eye(3) #diagonally we will get 1 as per no of element given in bracket
print(eye1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [52]:
eye2=np.eye(5)
print(eye2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
import os
os.getcwd()

'C:\\Users\\Admin'

In [54]:
#DIAGONAL MATRIX

d=np.diag([10,20,30,40])
d

array([[10,  0,  0,  0],
       [ 0, 20,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [55]:
e=np.diag([11,12,13,14,15,16])
e

array([[11,  0,  0,  0,  0,  0],
       [ 0, 12,  0,  0,  0,  0],
       [ 0,  0, 13,  0,  0,  0],
       [ 0,  0,  0, 14,  0,  0],
       [ 0,  0,  0,  0, 15,  0],
       [ 0,  0,  0,  0,  0, 16]])

In [56]:
#RANDOM

r=np.random.randn(10) #In randn n stand for negative #Gaussian
r

array([-0.21930218,  0.97044685,  0.04124102,  0.35461329, -0.10401558,
        0.04386168, -1.22222863,  1.31250227,  1.02779361, -0.46417107])

In [57]:
r1=np.random.rand(10) #random.rand only positive numbers randomly
r1

#All numbers will have uniform range 0-1

array([0.17552856, 0.11352866, 0.0055233 , 0.91023278, 0.55640849,
       0.01743645, 0.12084567, 0.85456973, 0.35123886, 0.58087162])

In [58]:
r2=np.random.rand(30).reshape(5,6)
r2

array([[0.49748517, 0.05315151, 0.34360168, 0.61001579, 0.36067055,
        0.46605403],
       [0.40007069, 0.70237705, 0.43040775, 0.12807069, 0.70719424,
        0.58353834],
       [0.28673995, 0.37518369, 0.62881985, 0.0730937 , 0.39981813,
        0.59199409],
       [0.96673998, 0.23790161, 0.82990692, 0.5989913 , 0.96161341,
        0.99328085],
       [0.10942177, 0.03115468, 0.08572629, 0.79672231, 0.51366095,
        0.17737674]])

In [59]:
y=np.random.randint(50,size=(45))
y

array([34, 25, 26, 32, 33, 26, 10, 45, 42, 14,  1,  7, 49, 14,  9, 49,  8,
        4, 33, 24, 39,  1, 22, 37, 23,  8, 46, 48,  8, 30, 43, 11, 38, 31,
       34, 19, 17,  2,  0, 47, 19, 25, 46, 18, 22])

In [60]:
z=np.random.randint(20,size=(3,5))
z
#randint give a range stop number and size it will pick up random integer and
#arrange it in given size array 

array([[10, 10,  5,  3, 15],
       [19,  7,  4,  1, 16],
       [ 5,  1,  5,  3, 19]])

In [61]:
x=np.random.randint(30,size=(3,5,2))
x

array([[[23,  7],
        [16, 25],
        [21,  2],
        [ 8, 12],
        [ 5, 28]],

       [[ 7,  6],
        [26, 29],
        [ 1,  9],
        [12,  2],
        [16,  3]],

       [[ 2, 16],
        [26, 13],
        [15, 20],
        [27, 27],
        [20,  5]]])

In [62]:
#choice
c=np.random.choice([5,7,9,10,15,20],size=(4,3))
c
#give ur number of choice to arrange in array in certain size

array([[10,  5,  9],
       [15, 15,  9],
       [10,  7, 20],
       [ 9, 20,  7]])

INDEXING & SLICING

In [63]:
np1=np.array([10,12,14,51,55,23,20,74,85])
np1

array([10, 12, 14, 51, 55, 23, 20, 74, 85])

In [64]:
np1[5] #indexing 

23

In [65]:
np1[-1]

85

In [66]:
#start stop #start stop step

np1[0:4]

array([10, 12, 14, 51])

In [67]:
np1[::-1]

array([85, 74, 20, 23, 55, 51, 14, 12, 10])

In [68]:
np2=np.arange(1,31).reshape(6,5)
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [69]:
np2[0]


array([1, 2, 3, 4, 5])

In [70]:
np2[0][2] #double indexing

3

In [71]:
np2[2][3]

14

In [72]:
np2[0:4]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [73]:
#from 1st 3 array last 3 data

np2[0:3,-3:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [74]:
#from last 3 array first 3 data
np2[-3:,0:3]

array([[16, 17, 18],
       [21, 22, 23],
       [26, 27, 28]])

In [75]:
np3=np.arange(1,31).reshape(1,5,6)
np3

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]])

In [76]:
np3[0,0:,-3:]#All arrays last 3 data

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30]])

In [77]:
#Last 4 arrays last 4 data
np3[0,-4:,-4:]


array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24],
       [27, 28, 29, 30]])

In [78]:
np1

array([10, 12, 14, 51, 55, 23, 20, 74, 85])

In [79]:
for i in np1:
    print(i,end=" ")

10 12 14 51 55 23 20 74 85 

In [80]:
np2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [81]:
for i in np2: #2D array we need 2 for loop to extract data
    for j in i:
        print(j,end="  ")

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  

In [82]:
np3

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]]])

In [83]:
for i in np3:#3D array we need 3 for loop to extract data
    for j in i:
        for k in j:
            print(k,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 

In [84]:
#nditer===== numpy dimensional iteration
#It extracts data from all layers and give us final output

for i in np.nditer(np1):
    print(i,end=" ")

10 12 14 51 55 23 20 74 85 

In [85]:
for i in np.nditer(np2):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 

In [86]:
for i in np.nditer(np3):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 

In [87]:
#getting output with index number
for idx,i in np.ndenumerate(np2):#ndenumerate numpy dimensional enumerate
    print(idx,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 7
(1, 2) 8
(1, 3) 9
(1, 4) 10
(2, 0) 11
(2, 1) 12
(2, 2) 13
(2, 3) 14
(2, 4) 15
(3, 0) 16
(3, 1) 17
(3, 2) 18
(3, 3) 19
(3, 4) 20
(4, 0) 21
(4, 1) 22
(4, 2) 23
(4, 3) 24
(4, 4) 25
(5, 0) 26
(5, 1) 27
(5, 2) 28
(5, 3) 29
(5, 4) 30


In [88]:
for idx,i in np.ndenumerate(np3):#ndenumerate numpy dimensional enumerate
    print(idx,i)



(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 0, 5) 6
(0, 1, 0) 7
(0, 1, 1) 8
(0, 1, 2) 9
(0, 1, 3) 10
(0, 1, 4) 11
(0, 1, 5) 12
(0, 2, 0) 13
(0, 2, 1) 14
(0, 2, 2) 15
(0, 2, 3) 16
(0, 2, 4) 17
(0, 2, 5) 18
(0, 3, 0) 19
(0, 3, 1) 20
(0, 3, 2) 21
(0, 3, 3) 22
(0, 3, 4) 23
(0, 3, 5) 24
(0, 4, 0) 25
(0, 4, 1) 26
(0, 4, 2) 27
(0, 4, 3) 28
(0, 4, 4) 29
(0, 4, 5) 30


In [89]:
nr1=np.array([["Satvika","Payal","Harry","Mohan"],[28,22,23,30]])
nr2=np.array([["Bcom","BAF","BSCIT","BMS"],[85.8,75.5,70,65],["MUmbai","Chennai","PUne","Thane"]])

In [90]:
nr1

array([['Satvika', 'Payal', 'Harry', 'Mohan'],
       ['28', '22', '23', '30']], dtype='<U11')

In [91]:
nr2

array([['Bcom', 'BAF', 'BSCIT', 'BMS'],
       ['85.8', '75.5', '70', '65'],
       ['MUmbai', 'Chennai', 'PUne', 'Thane']], dtype='<U32')

In [92]:
#CONCATENATE

nr3=np.concatenate((nr1,nr2))

In [93]:
nr3

array([['Satvika', 'Payal', 'Harry', 'Mohan'],
       ['28', '22', '23', '30'],
       ['Bcom', 'BAF', 'BSCIT', 'BMS'],
       ['85.8', '75.5', '70', '65'],
       ['MUmbai', 'Chennai', 'PUne', 'Thane']], dtype='<U32')

In [94]:
#STACK

nr1=np.array([["Satvika","Payal","Harry","Mohan"],[28,22,23,30]])
nr2=np.array([["Bcom","BAF","BSCIT","BMS"],["MUmbai","Chennai","PUne","Thane"]])

In [95]:
nr4=np.stack((nr1,nr2),axis=0)
nr4

#In stack both array will be in different 2D way and it will create a 3D array

array([[['Satvika', 'Payal', 'Harry', 'Mohan'],
        ['28', '22', '23', '30']],

       [['Bcom', 'BAF', 'BSCIT', 'BMS'],
        ['MUmbai', 'Chennai', 'PUne', 'Thane']]], dtype='<U11')

In [96]:
nr5=np.stack((nr1,nr2),axis=1)
nr5

array([[['Satvika', 'Payal', 'Harry', 'Mohan'],
        ['Bcom', 'BAF', 'BSCIT', 'BMS']],

       [['28', '22', '23', '30'],
        ['MUmbai', 'Chennai', 'PUne', 'Thane']]], dtype='<U11')

In [97]:
#HORIZONTAL STACK
print(nr1)
print(nr2)
nr6=np.hstack((nr1,nr2))
nr6

[['Satvika' 'Payal' 'Harry' 'Mohan']
 ['28' '22' '23' '30']]
[['Bcom' 'BAF' 'BSCIT' 'BMS']
 ['MUmbai' 'Chennai' 'PUne' 'Thane']]


array([['Satvika', 'Payal', 'Harry', 'Mohan', 'Bcom', 'BAF', 'BSCIT',
        'BMS'],
       ['28', '22', '23', '30', 'MUmbai', 'Chennai', 'PUne', 'Thane']],
      dtype='<U11')

In [98]:
#Vertical stack is similr to concatenate
print(nr1)
print(nr2)
nr7=np.vstack((nr1,nr2))
nr7

[['Satvika' 'Payal' 'Harry' 'Mohan']
 ['28' '22' '23' '30']]
[['Bcom' 'BAF' 'BSCIT' 'BMS']
 ['MUmbai' 'Chennai' 'PUne' 'Thane']]


array([['Satvika', 'Payal', 'Harry', 'Mohan'],
       ['28', '22', '23', '30'],
       ['Bcom', 'BAF', 'BSCIT', 'BMS'],
       ['MUmbai', 'Chennai', 'PUne', 'Thane']], dtype='<U11')

In [99]:
#SPLIT FUNCTION

nr8=np.array([100,200,300,400,500,600,700,800,900,1000])

In [100]:
nr9=np.array_split(nr8,12)
nr9

[array([100]),
 array([200]),
 array([300]),
 array([400]),
 array([500]),
 array([600]),
 array([700]),
 array([800]),
 array([900]),
 array([1000]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [101]:
#CHECKING DATATYPE


A=np.array(["Satvika Thakkar","Mohna","Marry","Harry"])
A

array(['Satvika Thakkar', 'Mohna', 'Marry', 'Harry'], dtype='<U15')

In [102]:
A.dtype #Dtype is function to check datatype

dtype('<U15')

In [103]:
B=np.array([1,2,4,5])
B
print(B.dtype)

int32


In [104]:
C=np.array([45.7,75.6,94.5,12.3])
print(C.dtype)

float64


In [105]:
#Astype function to change any type

C.astype("int32")

array([45, 75, 94, 12])

In [106]:
B.astype("float64")

array([1., 2., 4., 5.])

In [107]:
D=np.array(["1","2"])
print(D.dtype)

<U1


In [108]:
D.astype("int32")

array([1, 2])

BOARD CASTING ARITHMETIC OPERATIONS ON MATRIX & AGGREGATE FUNCTION

In [109]:
A=np.array([[10,20,30,40],[45,50,60,70]])
B=np.array([[10,5,35,45],[4,9,10,5]])

In [110]:
C=A+B

In [111]:
C

array([[20, 25, 65, 85],
       [49, 59, 70, 75]])

In [112]:
A-B

array([[ 0, 15, -5, -5],
       [41, 41, 50, 65]])

In [113]:
B-A

array([[  0, -15,   5,   5],
       [-41, -41, -50, -65]])

In [114]:
np.add(A,B)#A+B

array([[20, 25, 65, 85],
       [49, 59, 70, 75]])

In [115]:
np.subtract(A,B)

array([[ 0, 15, -5, -5],
       [41, 41, 50, 65]])

In [116]:
np.subtract(B,A)

array([[  0, -15,   5,   5],
       [-41, -41, -50, -65]])

In [117]:
A*B

array([[ 100,  100, 1050, 1800],
       [ 180,  450,  600,  350]])

In [118]:
np.multiply(A,B)

array([[ 100,  100, 1050, 1800],
       [ 180,  450,  600,  350]])

In [119]:
A/B

array([[ 1.        ,  4.        ,  0.85714286,  0.88888889],
       [11.25      ,  5.55555556,  6.        , 14.        ]])

In [120]:
np.divide(A,B)

array([[ 1.        ,  4.        ,  0.85714286,  0.88888889],
       [11.25      ,  5.55555556,  6.        , 14.        ]])

In [121]:
A

array([[10, 20, 30, 40],
       [45, 50, 60, 70]])

In [122]:
D=np.array([[2,2,2,2],[2,2,2,2]])

In [123]:
A%D

array([[0, 0, 0, 0],
       [1, 0, 0, 0]])

In [124]:
np.remainder(A,D)

array([[0, 0, 0, 0],
       [1, 0, 0, 0]])

SCALAR MATRIX

In [125]:
A

array([[10, 20, 30, 40],
       [45, 50, 60, 70]])

In [126]:
5*A

array([[ 50, 100, 150, 200],
       [225, 250, 300, 350]])

In [127]:
num=6

In [128]:
num*A

array([[ 60, 120, 180, 240],
       [270, 300, 360, 420]])

In [129]:
A+num

array([[16, 26, 36, 46],
       [51, 56, 66, 76]])

In [130]:
A-num

array([[ 4, 14, 24, 34],
       [39, 44, 54, 64]])

In [131]:
A/num

array([[ 1.66666667,  3.33333333,  5.        ,  6.66666667],
       [ 7.5       ,  8.33333333, 10.        , 11.66666667]])

AGGREGATE FUNCTIONS===== SUM,min,max,average,count, average===mean

In [132]:
E=np.array([[10,20,30],[1,2,3],[15,25,35]])

In [133]:
E

array([[10, 20, 30],
       [ 1,  2,  3],
       [15, 25, 35]])

In [134]:
print("SUM of all element:",E.sum())
print("MIN of all element:",E.min())
print("MAX of all element:",E.max())
print("mean of all element:",E.mean())
print("Average of all element:",np.average(E))
print("Product of all elements:",np.prod(E))

SUM of all element: 141
MIN of all element: 1
MAX of all element: 35
mean of all element: 15.666666666666666
Average of all element: 15.666666666666666
Product of all elements: 472500000


In [135]:
E

array([[10, 20, 30],
       [ 1,  2,  3],
       [15, 25, 35]])

In [136]:
#AGGREGATE FUNCTION EACH ARRAY POSITION WISE

print("SUM OF EACH ARRAY POSITION WISE :",E.sum(axis=0))
print("SUM OF EACH ARRAY :",E.sum(axis=1))

SUM OF EACH ARRAY POSITION WISE : [26 47 68]
SUM OF EACH ARRAY : [60  6 75]


In [137]:
#FIND ROW WISE AND COLUMN WISE MEAN, MIN, MAX,PROD

print("MEAN OF EACH ARRAY POSITION WISE :",E.mean(axis=0))
print("MEAN OF EACH ARRAY :",E.mean(axis=1))
print("MIN OF EACH ARRAY POSITION WISE :",E.min(axis=0))
print("MIN OF EACH ARRAY :",E.min(axis=1))
print("Max OF EACH ARRAY POSITION WISE :",E.max(axis=0))
print("Max OF EACH ARRAY :",E.max(axis=1))
print("PRODUCT OF EACH ARRAY POSITION WISE :",np.prod(E,axis=0))
print("PRODUCT OF EACH ARRAY :",np.prod(E,axis=1))

MEAN OF EACH ARRAY POSITION WISE : [ 8.66666667 15.66666667 22.66666667]
MEAN OF EACH ARRAY : [20.  2. 25.]
MIN OF EACH ARRAY POSITION WISE : [1 2 3]
MIN OF EACH ARRAY : [10  1 15]
Max OF EACH ARRAY POSITION WISE : [15 25 35]
Max OF EACH ARRAY : [30  3 35]
PRODUCT OF EACH ARRAY POSITION WISE : [ 150 1000 3150]
PRODUCT OF EACH ARRAY : [ 6000     6 13125]


In [138]:
np.median(E) #50% Quartile Q2

15.0

In [139]:
np.sqrt(E)

array([[3.16227766, 4.47213595, 5.47722558],
       [1.        , 1.41421356, 1.73205081],
       [3.87298335, 5.        , 5.91607978]])

In [140]:
#DOT MULTIPLY

n1=np.array([[2,3],[4,5]])
n2=np.array([[1,2],[2,1]])
print(n1)
print(n2)

[[2 3]
 [4 5]]
[[1 2]
 [2 1]]


In [141]:
dotmul=np.dot(n1,n2)
print(dotmul)

[[ 8  7]
 [14 13]]


BOOLEAN INDEXING

In [142]:
s=np.array(range(1,16)).reshape(3,5)
s

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [143]:
bool=s>8

In [144]:
print(bool)

[[False False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]]


In [145]:
s<5

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

TRIGNOMETRIC FUNCTION

In [146]:
print("Sin:",np.sin(60))
print("cos:",np.cos(60))
print("tan:",np.tan(60))
print("log:",np.log(8))

Sin: -0.3048106211022167
cos: -0.9524129804151563
tan: 0.320040389379563
log: 2.0794415416798357


In [153]:
import random
c=random.randrange(105,300,3)
print(c)

132
